"""Tool for multimodal vision support using Ollama moondream model."""

import os

def describe_image(image_path: str, prompt: str = "Please provide a highly detailed description of this technical diagram, flowchart, or architecture slide.") -> str:
    """
    Send an image to the local moondream model and return its description.

    This function enables the agent to extract text descriptions and analyses
    from image files. It uses the Ollama python client to communicate with the
    'moondream' multimodal vision model.

    Args:
        image_path (str): The absolute or relative path to the image file.
        prompt (str): The text prompt guiding the model's description.

    Returns:
        str: The text content generated by the vision model describing the image,
             or an error string if the request fails.
    """
    if not os.path.exists(image_path):
        return f"Error: Image not found at {image_path}"
    
    try:
        import ollama
        response = ollama.chat(
            model="moondream",
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                    "images": [image_path]
                }
            ]
        )
        return response["message"]["content"]
    except Exception as e:
        return f"Error describing image: {str(e)}"
