"""Tool for multimodal vision support using Ollama moondream model."""

import os

SUPPORTED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp"}
MAX_IMAGE_BYTES = 25 * 1024 * 1024

def describe_image(image_path: str, prompt: str = "Please provide a highly detailed description of this technical diagram, flowchart, or architecture slide.") -> str:
    """
    Send an image to the local moondream model and return its description.

    This function enables the agent to extract text descriptions and analyses
    from image files. It uses the Ollama python client to communicate with the
    'moondream' multimodal vision model.

    Args:
        image_path (str): The absolute or relative path to the image file.
        prompt (str): The text prompt guiding the model's description.

    Returns:
        str: The text content generated by the vision model describing the image,
             or an error string if the request fails.
    """
    if not os.path.exists(image_path):
        return f"Error: Image not found at {image_path}"
    if not os.path.isfile(image_path):
        return f"Error: Not a file: {image_path}"
    extension = os.path.splitext(image_path)[1].lower()
    if extension not in SUPPORTED_IMAGE_EXTENSIONS:
        return f"Error: Unsupported image type '{extension}'"
    if os.path.getsize(image_path) > MAX_IMAGE_BYTES:
        return "Error: Image exceeds the 25 MiB limit"
    prompt = str(prompt or "Describe this image.").strip()[:4000]
    
    try:
        import ollama
        response = ollama.chat(
            model="moondream",
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                    "images": [image_path]
                }
            ]
        )
        message = response.get("message") if isinstance(response, dict) else getattr(response, "message", None)
        content = message.get("content") if isinstance(message, dict) else getattr(message, "content", None)
        if not content:
            return "Error describing image: Ollama returned an empty response"
        return str(content)
    except Exception as e:
        return f"Error describing image: {str(e)}"
